### PR TITLE
SimpleRisk Release 20230106-001 + preparing Docker images to use PHP 8

### PR DESCRIPTION
**Pull request by WolfangAukang**
Now building the following images with PHP 8:
- `simplerisk`: [ubuntu:jammy](https://hub.docker.com/layers/library/ubuntu/jammy/images/sha256-817cfe4672284dcbfee885b1a66094fd907630d610cab329114d036716be49ba?context=explore)
- `simplerisk-minimal`:  [php:8.1-apache](https://hub.docker.com/layers/library/php/8.1-apache/images/sha256-e4b6a7ccb05664d58cdccb758eeaa3c10eafcedfb7a44ede56f710c89d1f589f?context=explore)

### CODE REVIEW

**Comment by WolfangAukang** [comment]
PR will be on draft as there are issues to fix

**Review by jsokol — APPROVED** [review]

**Comment by jsokol** [comment]
This PR is fine, but should not be merged until the next SimpleRisk release where it is compatible with PHP 8.

**Comment by jsokol** [comment]
@WolfangAukang FYI, SimpleRisk will only work with PHP 8.1, but it looks like you're doing a PHP 8.0 image.  I think we can skip that since it won't work.

**Comment by WolfangAukang** [comment]
Ready, I have removed PHP 8.0 from the list of images

**Comment by WolfangAukang** [comment]
Current check is failing because of the version update. When the code repository is updated, we can re run the check

**Pull request merged**
